import type { Metadata } from "next";
import "./globals.css";

import Header from "@/components/layout/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-bg text-white">
        <Header />
        <main className="mx-16 lg:mx-32 mt-20">{children}</main>
      </body>
    </html>
  );
}
